name: Run

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update submodules
        run: git submodule update --remote
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release --locked
      - name: Run graveyard_generator
        run: |
          cargo run --release --quiet > graveyard.md
          cat graveyard.md
      - name: Upload graveyard.md
        uses: actions/upload-artifact@v2
        with:
          path: graveyard.md
